# -*- coding: utf-8 -*-
"""notebook Amazon.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Lxl2tWNNLvcX4ztUj8_DOgZYr0zt6qi6

# **ML Terapan - Submission Akhir Membuat Model Sistem Rekomendasi**
- **Nama:** Lutfi Aundrie Hermawan
- **Email:** lutfiaunher@gmail.com
- **ID Dicoding:** A126YBF254

## **Import Library**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.impute import SimpleImputer
from sklearn.metrics import mean_squared_error, precision_score, recall_score, f1_score
from sklearn.metrics import mean_squared_error

"""## Data Preparation

Download Dataset USA Housing Dataset melalui Google Drive

[Google Drive](https://drive.google.com/file/d/1dMlIICJcmkKTsHVDFm263z6GTxtuvWek/view?usp=drive_link)

[Kaggle](https://www.kaggle.com/datasets/shivamb/amazon-prime-movies-and-tv-shows)

## **Mount to Drive**

Menghubungkan penyimpanan Google Drive ke Colab dan mengakses file yang disimpan di Google Drive langsung dari notebook.
"""

from google.colab import drive
drive.mount('/content/drive')

"""## **Read Dataset**

Memuat data dari csv ke dataframe
"""

df= pd.read_csv('/content/drive/MyDrive/Submission/Submission_One_ML_Terapan/amazon_prime_titles.csv')
df.head()

"""## Data Understanding

###**1. Dataset Information**

Melihat informasi dari dataframe. Dari informasi tersebut bahwa dataset memiliki jumlah data sebanyak 12 kolom dan 9668 baris
"""

df.info()

"""###**2. Check Missing Values**

Memeriksa nilai yang hilang (missing values) dalam dataset. Dari dataset ini bahwa missing values berjumlah 5 dimana presentasi missing values besar
"""

print("\nMissing values dalam dataset:")
print(df.isnull().sum())

missing_num = df[df.columns].isna().sum().sort_values(ascending=False)
missing_perc = (df[df.columns].isna().sum()/len(df)*100).sort_values(ascending=False)
missing = pd.concat([missing_num,missing_perc],keys=['Total','Percentage'],axis=1)
missing_train = missing[missing['Percentage']>0]
missing_train

"""Berdasarkan data pada dataset, terdapat nilai hilang (missing value) yang cukup tinggi pada kolom date_added dan country, yaitu dengan persentase di atas 90%. Oleh karena itu, solusi yang diambil adalah menghapus kolom tersebut karena jumlah data yang hilang terlalu banyak. Sementara itu, kolom director dan cast dapat diisi dengan nilai 'Other', dan kolom rating dapat diisi dengan ranting rata-rata."

## **Exploratory Data Analysis**

###**1. Tahun Rilis Terbanyak**

Visualisasi distribusi tahun rilis untuk Movie dan TV Show menunjukkan bahwa penambahan konten baru mengalami peningkatan signifikan pada rentang tahun 2015 hingga 2020. Pada periode ini, jumlah konten yang dirilis merupakan yang terbanyak dibandingkan tahun-tahun sebelumnya.
"""

# Pastikan kolom 'release_year' dalam format numerik
df['release_year'] = pd.to_numeric(df['release_year'], errors='coerce')

# Buat grup tahun (opsional, untuk mengurangi noise jika tahun sangat banyak)
bins = [1950, 1960, 1970, 1980, 1990, 2000, 2010, 2015, 2020, 2025]
labels = ['1950s', '1960s', '1970s', '1980s', '1990s', '2000s', '2010-14', '2015-19', '2020s']
df['year_group'] = pd.cut(df['release_year'], bins=bins, labels=labels)

# Plot menggunakan seaborn
plt.figure(figsize=(10, 6))
sns.countplot(data=df, x='year_group', hue='type', palette='Set3')
plt.title('Number of TV Shows and Movies by Release Year Group')
plt.xlabel('Release Year Group')
plt.ylabel('Count')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

"""###**2. Distribusi Rating Konten**

Distribusi konten berdasarkan rating menunjukkan bahwa Amazon Prime memiliki banyak konten yang ditujukan untuk audiens remaja. Hal ini terlihat dari dominasi kategori rating seperti "13+" dan "16+", yang merupakan dua kategori dengan jumlah konten terbanyak di platform tersebut.
"""

plt.figure(figsize=(10, 6))
sns.countplot(x='rating', order = df['rating'].value_counts().index, data = df)
plt.title('Distribution of content ratings on Amazon Prime')
plt.xlabel('Rating')
plt.ylabel('Count')
plt.xticks(rotation = 45)
plt.show()

"""### **3. Top Genre Amazon Prime**

Menvisualisasi genre top 5 di Amazon Prime. Visualisasi menunjukkan bahwa genre yang paling banyak ditampilkan dalam dataset adalah Drama, Comedy, Action, Suspense, dan Kids. Kelima genre ini merupakan genre terpopuler dengan jumlah konten terbanyak.
"""

genres = df['listed_in'].str.split(', ', expand=True).stack().value_counts()
plt.figure(figsize=(12, 8))
sns.barplot(x=genres.values[:5], y=genres.index[:5])
plt.title('Top 5 Genres on Amazon Prime')
plt.xlabel('Number of Titles')
plt.ylabel('Genre')
plt.show()

"""###**4. Distribusi Durasi Movie**

Visualisasi menunjukkan distribusi durasi film di Amazon Prime, dengan mayoritas Movie memiliki durasi antara 80 hingga 120 menit. Hal ini mencerminkan preferensi umum terhadap film berdurasi standar.
"""

# Filter hanya Movie
movies = df[df['type'] == 'Movie'].copy()

# Ambil hanya nilai durasi yang berformat menit (mengandung 'min')
movies = movies[movies['duration'].str.contains('min', na=False)]

# Hapus 'min' dan ubah ke numerik
movies['duration'] = movies['duration'].str.replace(' min', '', regex=False)
movies['duration'] = pd.to_numeric(movies['duration'], errors='coerce')

# Plot distribusi
plt.figure(figsize=(10, 6))
sns.histplot(movies['duration'].dropna(), bins=30, kde=True, color='coral')
plt.title('Distribusi Durasi Film di Amazon Prime')
plt.xlabel('Durasi (menit)')
plt.ylabel('Frekuensi')
plt.grid(True, linestyle='--', alpha=0.5)
plt.tight_layout()
plt.show()

"""###**5. Distribusi Durasi TV Series**

Visualisasi menunjukkan distribusi jumlah season pada TV Show di Amazon Prime. Mayoritas serial memiliki hanya 1 season, menunjukkan dominasi format mini series atau limited series di platform ini.
"""

# Filter hanya TV Show
tv_shows = df[df['type'] == 'TV Show'].copy()

# Ambil angka dari durasi (misalnya '2 Seasons' → 2)
tv_shows['seasons'] = tv_shows['duration'].str.extract('(\d+)').astype(float)

# Visualisasi distribusi jumlah season
plt.figure(figsize=(10, 6))
sns.countplot(x='seasons', data=tv_shows, color='lightgreen')
plt.title('Distribusi Jumlah Season pada TV Show di Amazon Prime')
plt.xlabel('Jumlah Season')
plt.ylabel('Jumlah TV Show')
plt.grid(True, linestyle='--', alpha=0.5)
plt.tight_layout()
plt.show()

"""## **Data Preparation**

###**1. Handling Missing Values**

Nilai yang hilang pada kolom director dan cast akan diimputant dengan data "unknown" sedangkan kolom rating akan diisi dengan modus.
"""

# Imputant missing values
df['director'] = df['director'].fillna('Unknown')
df['cast'] = df['cast'].fillna('Unknown')
df['rating'] = df['rating'].fillna(df['rating'].mode()[0])

"""Menghapus kolom date_added dan country dikarenakan nilai yang hilang terlalu banyak"""

# remove country and date_added
df = df.drop(['country','date_added'], axis=1)

"""Cek kembali Missing Value setelah dilakukan Handling"""

# Cek missing values
missing_values = df.isnull().sum()
print(missing_values)

"""### **2. Replace Rating**

Dalam dataset, ada beberapa nilai yang sebenarnya sama, tetapi ditulis dengan nama atau format yang berbeda. Untuk membuat data lebih konsisten dan mudah dianalisis, nama-nama tersebut diganti atau diseragamkan menjadi satu format yang sama.
"""

#basically we are replacing the names to make it less cluster
df['rating']=df['rating'].replace({
    "16": "16+",
    "AGES_16_": "16+",
    "AGES_18_": "18+",
    "R": "18+",
    "NC-17": "18+",
    "13+": "PG-13",
    "PG-13": "PG-13",
    "G": "GENERAL",
    "ALL": "GENERAL",
    "ALL_AGES": "GENERAL",
    "UNRATED": "UNRATED",
    "NOT_RATE": "UNRATED",
    "NR": "UNRATED",
    "7+": "TV-Y7",
    "TV-NR": "TV-UNRATED"
})

"""### **3. Mengkategorikan Duration**

Memisahkan antara waktu movie dengan season
"""

df['duration_by_min']=df['duration'].str.split('min',expand=True)[0]
df.head()

"""Mendefinisikan duration by min"""

def condi(x):
    if 'min' in x:
        return int(x.split()[0])
    else:
        return 0
df['duration_in_min']=df['duration'].apply(condi)

df.head()

"""Mendefinisikan duration by season"""

def condi(x):
    if 'season' in x:
        return int(x.split()[0])
    else:
        return 0
df['duration_in_seasons']=df['duration'].apply(condi)

df.head()

df['show_id'] = df['show_id'].str.replace('s', '')

df['duration_in_min'] = df['duration_in_min'].astype(int)
df['duration_in_seasons'] = df['duration_in_seasons'].astype(int)
df['show_id'] = df['show_id'].astype(int)

"""Hapus apabila tidak diperlukan"""

df=df.drop(columns=['duration'], axis=1)

df_clean=df.copy()

"""##**Modelling**

###**1. Model Development Content Based Filtering**

Digunakan untuk merekomendasikan film atau TV show berdasarkan kemiripan konten seperti genre, deskripsi, sutradara, dll.
"""

df_CBF=df_clean.copy()

# Ambil kolom yang relevan
df_CBF['combined_features'] = df_CBF['title'].fillna('') + ' ' + \
                          df_CBF['director'].fillna('') + ' ' + \
                          df_CBF['cast'].fillna('') + ' ' + \
                          df_CBF['listed_in'].fillna('') + ' ' + \
                          df_CBF['description'].fillna('')

# Ubah ke dalam bentuk vektor TF-IDF
tfidf = TfidfVectorizer(stop_words='english')
tfidf_matrix = tfidf.fit_transform(df_CBF['combined_features'])

# Cek hasil vektorisasi
print(f"TF-IDF Matrix Shape: {tfidf_matrix.shape}")

# Konversi TF-IDF matrix ke bentuk dense dan buat DataFrame
tfidf_df = pd.DataFrame(
    tfidf_matrix.todense(),
    columns=tfidf.get_feature_names_out(),
    index=df_CBF['title']
)

# Tampilkan 5 baris pertama
print(tfidf_df.head())

# Hitung kemiripan antar konten
cosine_sim = cosine_similarity(tfidf_matrix, tfidf_matrix)

# Buat mapping antara judul dan index DataFrame
indices = pd.Series(df.index, index=df_CBF['title'].str.lower()).drop_duplicates()

"""Matriks Kemiripan Antar Judul"""

cosine_sim_df = pd.DataFrame(cosine_sim,
                             index=df_CBF['title'],
                             columns=df_CBF['title'])
print(f"Cosine Similarity Matrix Shape: {cosine_sim_df.shape}")

print("Sample Cosine Similarity Matrix:")
print(cosine_sim_df.sample(5, axis=1, random_state=42).sample(10, axis=0, random_state=42)
)

"""#### **Sistem Rekomendasi**"""

# Hitung cosine similarity
cosine_sim = cosine_similarity(tfidf_matrix, tfidf_matrix)

# Membuat fungsi rekomendasi berbasis konten
def get_recommendations(title, df_CBF, cosine_sim_matrix, top_n=10):
    title = title.strip()

    # Cek apakah judul ada di DataFrame
    if title not in df_CBF['title'].values:
        return f"[ERROR] Judul '{title}' tidak ditemukan dalam dataset."

    # Temukan indeks berdasarkan judul
    idx = df_CBF[df_CBF['title'] == title].index[0]

    # Ambil skor similarity untuk semua item
    sim_scores = list(enumerate(cosine_sim_matrix[idx]))

    # Urutkan berdasarkan similarity tertinggi
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)

    # Ambil top_n hasil teratas, selain dirinya sendiri (index 0)
    top_indices = [i[0] for i in sim_scores[1:top_n+1]]

    # Ambil judul film/TV show sebagai hasil
    recommended = df_CBF[['title', 'type', 'listed_in']].iloc[top_indices]
    recommended['similarity_score'] = [sim_scores[i+1][1] for i in range(top_n)]

    return recommended.reset_index(drop=True)

# Contoh penggunaan
recommendations = get_recommendations("Halloween Heroes", df_CBF, cosine_sim)
print(recommendations)

"""####**Evaluasi Model Development Content Based Filtering**"""

relevant_movies = [
    'Faster',
    'Halloween Kids Songs by Little Baby Bum',
    'Halloween Heroes',
    '27 September'
]

def precision_at_k(recommended, relevant, k):
    if not recommended or k == 0:
        return 0.0
    recommended_at_k = set(recommended[:k])
    relevant_set = set(relevant)
    precision = len(recommended_at_k & relevant_set) / k
    return round(precision, 4)

def recall_at_k(recommended, relevant, k):
    if not relevant:
        return 0.0
    recommended_at_k = set(recommended[:k])
    relevant_set = set(relevant)
    recall = len(recommended_at_k & relevant_set) / len(relevant_set)
    return round(recall, 4)

def f1_score_at_k(recommended, relevant, k):
    precision = precision_at_k(recommended, relevant, k)
    recall = recall_at_k(recommended, relevant, k)
    if precision + recall == 0:
        return 0.0
    f1 = 2 * (precision * recall) / (precision + recall)
    return round(f1, 4)

def evaluate_recommendation_system(query_title, ground_truth, k=10):
    try:
        recommendations = get_recommendations(query_title, df_clean, cosine_sim)

        # Extract list of recommended titles
        recommended_titles = recommendations['title'].tolist()

        precision = precision_at_k(recommended_titles, ground_truth, k)
        recall = recall_at_k(recommended_titles, ground_truth, k)
        f1 = f1_score_at_k(recommended_titles, ground_truth, k)

        print(f"\nEvaluation for: '{query_title}'")
        print(f"Top-{k} Recommendations: {recommended_titles[:k]}")
        print(f"Ground Truth: {ground_truth}")
        print(f"\nPrecision@{k}: {precision}")
        print(f"Recall@{k}:    {recall}")
        print(f"F1-Score@{k}:  {f1}")

        return {
            "precision": precision,
            "recall": recall,
            "f1_score": f1
        }

    except Exception as e:
        print(f"[ERROR] Gagal mengevaluasi: {e}")
        return None


evaluate_recommendation_system("The Cat in the Hat Knows a Lot About Halloween!", relevant_movies, k=10)

"""###**2. Model Development Collaborative Filtering**"""

df_CF=df_clean.copy()

from sklearn.preprocessing import LabelEncoder
import pandas as pd

df_CF['userId'] = np.random.randint(1, 1001, df_CF.shape[0])
df_CF['movseri_id'] = df_CF['show_id'].astype('category').cat.codes

# Initialize LabelEncoder
label_encoder = LabelEncoder()

# Apply Label Encoding to the 'Color' column
df_CF['rating'] = label_encoder.fit_transform(df_CF['rating'])

df_collab = df_CF[['userId', 'movseri_id', 'rating']]

# Cek data
df_collab.head()

train_data, test_data = train_test_split(df_collab, test_size=0.3, random_state=42)

from sklearn.model_selection import train_test_split

# Bagi data
train_data, test_data = train_test_split(df_collab, test_size=0.2, random_state=42)

# Ambil input dan konversi ke int32
train_user_input = train_data['userId'].values.astype(np.int32)
train_item_input = train_data['movseri_id'].values.astype(np.int32)
train_ratings = train_data['rating'].values.astype(np.float32)

test_user_input = test_data['userId'].values.astype(np.int32)
test_item_input = test_data['movseri_id'].values.astype(np.int32)
test_ratings = test_data['rating'].values.astype(np.float32)

"""#### **Neural Collaborative Filtering (NCF)**"""

from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Embedding, Flatten, Dense, Concatenate
from tensorflow.keras.optimizers import Adam
import numpy as np
import tensorflow as tf # Import tensorflow
from tensorflow.keras.metrics import MeanSquaredError
import tensorflow.keras.backend as K # Import Keras backend as K


# Parameter
num_users = df_collab['userId'].nunique()
num_items = df_collab['movseri_id'].nunique()
embedding_dim = 50

train_user_input = np.clip(train_user_input, 0, num_users - 1)
train_item_input = np.clip(train_item_input, 0, num_items - 1)

# Cek dimensi dan validasi
assert train_user_input.min() >= 0 and train_user_input.max() <= num_users - 1, "User ID tidak valid!"
assert train_item_input.min() >= 0 and train_item_input.max() <= num_items - 1, "Movie ID tidak valid!"
train_user_input = train_user_input.flatten()
train_item_input = train_item_input.flatten()

# Model NCF

# Input layer
user_input = Input(shape=(1,))
item_input = Input(shape=(1,))

# Embedding layer
user_embed = Embedding(input_dim=num_users, output_dim=embedding_dim)(user_input)
item_embed = Embedding(input_dim=num_items, output_dim=embedding_dim)(item_input)

# Flatten layer
user_vec = Flatten()(user_embed)
item_vec = Flatten()(item_embed)

# Concatenate user and item vectors
merged = Concatenate()([user_vec, item_vec])

# Dense layers
x = Dense(64, activation='relu')(merged)
output = Dense(1)(x)

# Fungsi untuk menghitung RMSE
def rmse(y_true, y_pred):
    return K.sqrt(K.mean(K.square(y_pred - y_true))) # Now K is defined

# Membuat dan kompilasi model
model = Model(inputs=[user_input, item_input], outputs=output)

# Compile model dengan MSE dan RMSE sebagai metrik
model.compile(optimizer=Adam(),
              loss='mean_squared_error',
              metrics=[MeanSquaredError(),
                       rmse])

# Menampilkan summary model
model.summary()

# Pastikan train_ratings memiliki tipe data yang sesuai
train_ratings = train_ratings.astype(np.float32)

# Melatih model
history = model.fit(
    [train_user_input, train_item_input],  # dua input
    train_ratings,  # target ratings
    epochs=40,
    batch_size=64
)

import numpy as np

# Fungsi untuk mendapatkan rekomendasi film berdasarkan prediksi rating
def get_movie_recommendations(user_id, num_recommendations=10):
    # Semua ID film yang tersedia
    movseri_ids = np.arange(num_items)

    # Membuat array user_id dengan panjang sama
    user_ids = np.full_like(movseri_ids, user_id)

    # Prediksi rating untuk semua (user_id, movie_id)
    predictions = model.predict([user_ids, movseri_ids], verbose=0).flatten()

    # Ambil ID film dengan rating tertinggi
    top_indices = predictions.argsort()[::-1][:num_recommendations]
    recommended_ids = movseri_ids[top_indices]

    # Ambil data film dari df_CF (berdasarkan movseri_id)
    recommended_movies = df_CF[df_CF['movseri_id'].isin(recommended_ids)][['title', 'listed_in']].drop_duplicates()

    return recommended_movies.reset_index(drop=True)

# Contoh: Mendapatkan 10 rekomendasi film untuk user tertentu
user_id = 70  # Ganti dengan ID user yang ingin diuji

# Ambil rekomendasi dari fungsi
recommended_movies = get_movie_recommendations(user_id, num_recommendations=10)

# Tampilkan hasil rekomendasi
print(f"Top 10 rekomendasi film untuk user {user_id}:\n")
for i, row in recommended_movies.iterrows():
    print(f"{i+1}. Title: {row['title']}  |  Genre: {row['listed_in']}")

"""####**Evaluasi Collaborative Filtering**"""

import matplotlib.pyplot as plt

# Mengambil data MSE dan RMSE dari history
mse = history.history['mean_squared_error']
rmse = history.history['rmse']

# Membuat plot MSE selama training
plt.figure(figsize=(12, 6))

# Plot MSE
plt.subplot(1, 2, 1)
plt.plot(mse)
plt.title('Model Mean Squared Error (MSE) During Training')
plt.xlabel('Epoch')
plt.ylabel('MSE')

# Plot RMSE
plt.subplot(1, 2, 2)
plt.plot(rmse)
plt.title('Model Root Mean Squared Error (RMSE) During Training')
plt.xlabel('Epoch')
plt.ylabel('RMSE')

plt.tight_layout()
plt.show()