# -*- coding: utf-8 -*-
"""notebook.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rChcRQzipI7c06tva7LLid5sW3kphlT9

# **ML Terapan - Submission Akhir Membuat Model Sistem Rekomendasi**
- **Nama:** Lutfi Aundrie Hermawan
- **Email:** lutfiaunher@gmail.com
- **ID Dicoding:** A126YBF254

## **Import Library**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.impute import SimpleImputer
from sklearn.metrics import mean_squared_error, precision_score, recall_score, f1_score
from sklearn.metrics import mean_squared_error

"""## Data Preparation

Download Dataset Amazon Prime Movies and TV Shows melalui Google Drive

[Google Drive](https://drive.google.com/drive/folders/1uqDIWoNldmUZi_kiGxlpiLSsVmsmVPHz?usp=sharing)

[Kaggle](https://www.kaggle.com/datasets/dgoenrique/amazon-prime-movies-and-tv-shows/data)

## **Mount to Drive**

Menghubungkan penyimpanan Google Drive ke Colab dan mengakses file yang disimpan di Google Drive langsung dari notebook.
"""

from google.colab import drive
drive.mount('/content/drive')

"""## **Read Dataset**

Memuat data dari csv ke dataframe
"""

df= pd.read_csv('/content/drive/MyDrive/Submission/Submission_One_ML_Terapan/Amazon_Prime_Video/titles.csv')
df.head()

df_credits= pd.read_csv('/content/drive/MyDrive/Submission/Submission_One_ML_Terapan/Amazon_Prime_Video/credits.csv')
df_credits.head()

"""## Data Understanding

###**1. Dataset Information**

Melihat informasi dari dataframe. Dari informasi tersebut bahwa dataset memiliki jumlah data sebanyak 12 kolom dan 9668 baris
"""

df.info()

"""Melihat informasi dari dataframe. Dari informasi tersebut bahwa dataset memiliki jumlah data sebanyak 5 kolom dan 140553 baris"""

df_credits.info()

"""###**2. Check Missing Values**

Memeriksa nilai yang hilang (missing values) dalam dataset. Dari dataset ini bahwa missing values berjumlah 5 dimana presentasi missing values besar
"""

print("\nMissing values dalam dataset:")
print(df.isnull().sum())

missing_num = df[df.columns].isna().sum().sort_values(ascending=False)
missing_perc = (df[df.columns].isna().sum()/len(df)*100).sort_values(ascending=False)
missing = pd.concat([missing_num,missing_perc],keys=['Total','Percentage'],axis=1)
missing_train = missing[missing['Percentage']>0]
missing_train

"""Berdasarkan data pada dataset, terdapat nilai hilang (missing value) yang cukup tinggi pada kolom seasons dan age_certification, yaitu dengan persentase di atas 60%. Namun untuk "seasons" tidak perlu didrop dikarenakan pada "typre : Movie" tidak ada season dan hanya perlu diisi nilai 0. Sedangkan "age_certification" untuk nilai kosong diisi "UnRated"

## **Exploratory Data Analysis**

###**1. Tahun Rilis Terbanyak**

Visualisasi distribusi tahun rilis untuk Movie dan TV Show menunjukkan bahwa penambahan konten baru mengalami peningkatan signifikan pada rentang tahun 2015 hingga 2020. Pada periode ini, jumlah konten yang dirilis merupakan yang terbanyak dibandingkan tahun-tahun sebelumnya.
"""

# Pastikan kolom 'release_year' dalam format numerik
df['release_year'] = pd.to_numeric(df['release_year'], errors='coerce')

# Buat grup tahun (opsional, untuk mengurangi noise jika tahun sangat banyak)
bins = [1950, 1960, 1970, 1980, 1990, 2000, 2010, 2015, 2020, 2025]
labels = ['1950s', '1960s', '1970s', '1980s', '1990s', '2000s', '2010-14', '2015-19', '2020s']
df['year_group'] = pd.cut(df['release_year'], bins=bins, labels=labels)

# Plot menggunakan seaborn
plt.figure(figsize=(10, 6))
sns.countplot(data=df, x='year_group', hue='type', palette='Set3')
plt.title('Number of TV Shows and Movies by Release Year Group')
plt.xlabel('Release Year Group')
plt.ylabel('Count')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

"""###**2. Distribusi Age Certification**

Distribusi konten berdasarkan Age Certification menunjukkan bahwa Amazon Prime memiliki banyak konten yang ditujukan untuk audiens remaja. Hal ini terlihat dari dominasi kategori Age Certification seperti "R" dan "PG-13", yang merupakan dua kategori dengan jumlah konten terbanyak di platform tersebut.
"""

plt.figure(figsize=(10, 6))
sns.countplot(x='age_certification', order = df['age_certification'].value_counts().index, data = df)
plt.title('Distribution of content Age Certification on Amazon Prime')
plt.xlabel('Age Certification')
plt.ylabel('Count')
plt.xticks(rotation = 45)
plt.show()

"""### **3. Top Genre Amazon Prime**

Menvisualisasi genre top 5 di Amazon Prime. Visualisasi menunjukkan bahwa genre yang paling banyak ditampilkan dalam dataset adalah Drama, Comedy, Thriller, Action, dan Romance. Kelima genre ini merupakan genre terpopuler dengan jumlah konten terbanyak.
"""

import ast

# Ubah string list menjadi list Python menggunakan ast.literal_eval
df['genres'] = df['genres'].apply(ast.literal_eval)

# Hitung frekuensi genre
genre_counts = df.explode('genres')['genres'].value_counts()

plt.figure(figsize=(12, 8))
sns.barplot(x=genre_counts.values[:5], y=genre_counts.index[:5])
plt.title('Top 5 Genres on Amazon Prime')
plt.xlabel('Number of Titles')
plt.ylabel('Genre')
plt.show()

"""###**4. Distribusi Durasi Movie**

Visualisasi menunjukkan distribusi durasi film di Amazon Prime, dengan mayoritas Movie memiliki durasi antara 80 hingga 120 menit. Hal ini mencerminkan preferensi umum terhadap film berdurasi standar.
"""

# Plot distribusi
plt.figure(figsize=(10, 6))
sns.histplot(df['runtime'].dropna(), bins=30, kde=True, color='coral')
plt.title('Distribusi Durasi Film di Amazon Prime')
plt.xlabel('Durasi (menit)')
plt.ylabel('Frekuensi')
plt.grid(True, linestyle='--', alpha=0.5)
plt.tight_layout()
plt.show()

"""###**5. Distribusi Durasi TV Series**

Visualisasi menunjukkan distribusi jumlah season pada TV Show di Amazon Prime. Mayoritas serial memiliki hanya 1 season, menunjukkan dominasi format mini series atau limited series di platform ini.
"""

# Visualisasi distribusi jumlah season
plt.figure(figsize=(10, 6))
sns.countplot(x='seasons', data=df, color='lightgreen')
plt.title('Distribusi Jumlah Season pada TV Show di Amazon Prime')
plt.xlabel('Jumlah Season')
plt.ylabel('Jumlah TV Show')
plt.grid(True, linestyle='--', alpha=0.5)
plt.tight_layout()
plt.show()

"""###**6. Distribusi Rating IMBD Score**

Visualisasi menunjukkan bahwa skor IMBD rata rata sekitar 6 - 6,5 dari 10 untuk keseluruhan movie maupun TV series
"""

plt.figure(figsize=(10, 6))
sns.histplot(df['imdb_score'].dropna(), kde=True, color='coral')
plt.title('Distribusi IMDB Score di Amazon Prime') # Corrected title
plt.xlabel('IMDB Score') # Corrected xlabel
plt.ylabel('Frekuensi')
plt.grid(True, linestyle='--', alpha=0.5)
plt.tight_layout()
plt.show()

"""## **Data Preparation**

###**Handling Missing Values**

Nilai yang hilang pada kolom Age Certification akan diimputant dengan data "Unrated"
"""

df['age_certification'] = df['age_certification'].fillna('Unrated')

"""Nilai yang hilang pada kolom Seasons akan diisi dengan data "0" dikarenakan tidak ada season"""

df['seasons'] = df['seasons'].fillna(0)

"""Untuk nilai yang hilang pada akan diimputant"""

df['imdb_score'] = df['imdb_score'].fillna(df['imdb_score'].median())
df['tmdb_score'] = df['tmdb_score'].fillna(df['tmdb_score'].median())
df['tmdb_popularity'] = df['tmdb_popularity'].fillna(df['tmdb_popularity'].median())
df['imdb_votes'] = df['imdb_votes'].fillna(0)
df['description'] = df['description'].fillna('No description available.')

df['has_imdb'] = df['imdb_id'].notna()

"""Cek kembali Missing Value setelah dilakukan Handling"""

# Cek missing values
missing_values = df.isnull().sum()
print(missing_values)

"""Hapus apabila tidak diperlukan

### **Handling Data**

Mengekstrak genre pertama dan negara produksi pertama dari kolom yang berisi string list
"""

# Pastikan kolom 'genres' dan 'production_countries' adalah string
df['genres'] = df['genres'].astype(str)
df['production_countries'] = df['production_countries'].astype(str)

# Mengekstrak genre pertama dan negara produksi pertama dari kolom yang berisi string list
df['genres'] = df['genres'].str.replace('[', '', regex=False)\
                                   .str.replace(']', '', regex=False)\
                                   .str.replace("'", '', regex=False)
df['genre'] = df['genres'].str.split(',').str[0].str.strip()

# Assuming you meant to clean 'production_countries' column in the 'df' DataFrame
df['production_countries'] = df['production_countries'].str.replace('[', '', regex=False)\
                                                               .str.replace(']', '', regex=False)\
                                                               .str.replace("'", '', regex=False)
df['production_country'] = df['production_countries'].str.split(',').str[0].str.strip()

"""Pisahkan kolom Role "DIRECTOR" dan "ACTORS"
"""

# Pisahkan DIRECTOR
directors = df_credits[df_credits['role'] == 'DIRECTOR'].groupby('id')['name'].first().reset_index()
directors.columns = ['id', 'director']
print(directors.head())

actors = df_credits[df_credits['role'] == 'ACTOR'].groupby('id')['name'].apply(lambda x: ', '.join(x)).reset_index()
actors.columns = ['id', 'cast']
print(actors.head())

"""Gabungkan kolom df_credits ke df"""

df = df.merge(directors, on='id', how='left')
df = df.merge(actors, on='id', how='left')

df_clean=df.copy()

"""### 4. Feature Engineering

Menggabungkan berbagai kolom teks (seperti title, director, cast, listed_in, dan description) menjadi satu kolom baru content. Hal ini dilakukan untuk memberikan representasi teks yang lebih komprehensif tentang film atau acara yang ada.
"""

df_CBF=df_clean.copy()

# Ambil kolom yang relevan
df_CBF['combined_features'] = df_CBF[['title', 'description', 'cast', 'genres', 'director']] \
                    .fillna('').agg(' '.join, axis=1)

df_CBF.info()

"""### 5. Transformasi Teks ke Vektor Numerik menggunakan TF-IDF Vectorizer"""

# Ubah ke dalam bentuk vektor TF-IDF
tfidf = TfidfVectorizer(stop_words='english')
tfidf_matrix = tfidf.fit_transform(df_CBF['combined_features'])

# Cek hasil vektorisasi
print(f"TF-IDF Matrix Shape: {tfidf_matrix.shape}")

# Konversi TF-IDF matrix ke bentuk dense dan buat DataFrame
tfidf_df = pd.DataFrame(
    tfidf_matrix.todense(),
    columns=tfidf.get_feature_names_out(),
    index=df_CBF['title']
)

# Tampilkan 5 baris pertama
print(tfidf_df.head())

"""##**Modelling**

###**1. Model Development Content Based Filtering**

Digunakan untuk merekomendasikan film atau TV show berdasarkan kemiripan konten seperti genre, deskripsi, sutradara, dll.
"""

# Hitung kemiripan antar konten
cosine_sim = cosine_similarity(tfidf_matrix, tfidf_matrix)

# Buat mapping antara judul dan index DataFrame
indices = pd.Series(df.index, index=df_CBF['title'].str.lower()).drop_duplicates()

"""Matriks Kemiripan Antar Judul"""

cosine_sim_df = pd.DataFrame(cosine_sim,
                             index=df_CBF['title'],
                             columns=df_CBF['title'])
print(f"Cosine Similarity Matrix Shape: {cosine_sim_df.shape}")

print("Sample Cosine Similarity Matrix:")
print(cosine_sim_df.sample(5, axis=1, random_state=42).sample(10, axis=0, random_state=42)
)

"""#### **Sistem Rekomendasi**"""

# Hitung cosine similarity
cosine_sim = cosine_similarity(tfidf_matrix, tfidf_matrix)

# Membuat fungsi rekomendasi berbasis konten
def get_recommendations(title, df_CBF, cosine_sim_matrix, top_n=10):
    title = title.strip()

    # Cek apakah judul ada di DataFrame
    if title not in df_CBF['title'].values:
        return f"[ERROR] Judul '{title}' tidak ditemukan dalam dataset."

    # Temukan indeks berdasarkan judul
    idx = df_CBF[df_CBF['title'] == title].index[0]

    # Ambil skor similarity untuk semua item
    sim_scores = list(enumerate(cosine_sim_matrix[idx]))

    # Urutkan berdasarkan similarity tertinggi
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)

    # Ambil top_n hasil teratas, selain dirinya sendiri (index 0)
    top_indices = [i[0] for i in sim_scores[1:top_n+1]]

    # Ambil judul film/TV show sebagai hasil
    recommended = df_CBF[['title', 'type', 'genres']].iloc[top_indices]
    recommended['similarity_score'] = [sim_scores[i+1][1] for i in range(top_n)]

    return recommended.reset_index(drop=True)

# Contoh penggunaan
recommendations = get_recommendations("Digging to Death", df_CBF, cosine_sim)
print(recommendations)

"""####**Evaluasi Model Development Content Based Filtering**"""

relevant_movies = [
    'Putham Pudhu Kaalai ',
    'Digging to Death',
    'All Through the House',
    'Sita Ramam'
]

def precision_at_k(recommended, relevant, k):
    if not recommended or k == 0:
        return 0.0
    recommended_at_k = set(recommended[:k])
    relevant_set = set(relevant)
    precision = len(recommended_at_k & relevant_set) / k
    return round(precision, 4)

def recall_at_k(recommended, relevant, k):
    if not relevant:
        return 0.0
    recommended_at_k = set(recommended[:k])
    relevant_set = set(relevant)
    recall = len(recommended_at_k & relevant_set) / len(relevant_set)
    return round(recall, 4)

def f1_score_at_k(recommended, relevant, k):
    precision = precision_at_k(recommended, relevant, k)
    recall = recall_at_k(recommended, relevant, k)
    if precision + recall == 0:
        return 0.0
    f1 = 2 * (precision * recall) / (precision + recall)
    return round(f1, 4)

def evaluate_recommendation_system(query_title, ground_truth, k=10):
    try:
        recommendations = get_recommendations(query_title, df_clean, cosine_sim)

        # Extract list of recommended titles
        recommended_titles = recommendations['title'].tolist()

        precision = precision_at_k(recommended_titles, ground_truth, k)
        recall = recall_at_k(recommended_titles, ground_truth, k)
        f1 = f1_score_at_k(recommended_titles, ground_truth, k)

        print(f"\nEvaluation for: '{query_title}'")
        print(f"Top-{k} Recommendations: {recommended_titles[:k]}")
        print(f"Ground Truth: {ground_truth}")
        print(f"\nPrecision@{k}: {precision}")
        print(f"Recall@{k}:    {recall}")
        print(f"F1-Score@{k}:  {f1}")

        return {
            "precision": precision,
            "recall": recall,
            "f1_score": f1
        }

    except Exception as e:
        print(f"[ERROR] Gagal mengevaluasi: {e}")
        return None


evaluate_recommendation_system("Bleed", relevant_movies, k=10)

"""###**2. Model Development Collaborative Filtering**"""

df_CF=df_clean.copy()

from sklearn.preprocessing import LabelEncoder
import pandas as pd

df_CF['userId'] = np.random.randint(1, 1001, df_CF.shape[0])
df_CF['movseri_id'] = df_CF['id'].astype('category').cat.codes

df_collab = df_CF[['userId', 'movseri_id', 'imdb_score']]

# Cek data
df_collab.head()

train_data, test_data = train_test_split(df_collab, test_size=0.3, random_state=42)

from sklearn.model_selection import train_test_split

# Bagi data
train_data, test_data = train_test_split(df_collab, test_size=0.2, random_state=42)

# Ambil input dan konversi ke int32
train_user_input = train_data['userId'].values.astype(np.int32)
train_item_input = train_data['movseri_id'].values.astype(np.int32)
train_ratings = train_data['imdb_score'].values.astype(np.float32)

test_user_input = test_data['userId'].values.astype(np.int32)
test_item_input = test_data['movseri_id'].values.astype(np.int32)
test_ratings = test_data['imdb_score'].values.astype(np.float32)

"""#### **Neural Collaborative Filtering (NCF)**"""

from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Embedding, Flatten, Dense, Concatenate
from tensorflow.keras.optimizers import Adam
import numpy as np
import tensorflow as tf # Import tensorflow
from tensorflow.keras.metrics import MeanSquaredError
import tensorflow.keras.backend as K # Import Keras backend as K


# Parameter
num_users = df_collab['userId'].nunique()
num_items = df_collab['movseri_id'].nunique()
embedding_dim = 50

train_user_input = np.clip(train_user_input, 0, num_users - 1)
train_item_input = np.clip(train_item_input, 0, num_items - 1)

# Cek dimensi dan validasi
assert train_user_input.min() >= 0 and train_user_input.max() <= num_users - 1, "User ID tidak valid!"
assert train_item_input.min() >= 0 and train_item_input.max() <= num_items - 1, "Movie ID tidak valid!"
train_user_input = train_user_input.flatten()
train_item_input = train_item_input.flatten()

# Model NCF

# Input layer
user_input = Input(shape=(1,))
item_input = Input(shape=(1,))

# Embedding layer
user_embed = Embedding(input_dim=num_users, output_dim=embedding_dim)(user_input)
item_embed = Embedding(input_dim=num_items, output_dim=embedding_dim)(item_input)

# Flatten layer
user_vec = Flatten()(user_embed)
item_vec = Flatten()(item_embed)

# Concatenate user and item vectors
merged = Concatenate()([user_vec, item_vec])

# Dense layers
x = Dense(64, activation='relu')(merged)
output = Dense(1)(x)

# Fungsi untuk menghitung RMSE
def rmse(y_true, y_pred):
    return K.sqrt(K.mean(K.square(y_pred - y_true))) # Now K is defined

# Membuat dan kompilasi model
model = Model(inputs=[user_input, item_input], outputs=output)

# Compile model dengan MSE dan RMSE sebagai metrik
model.compile(optimizer=Adam(),
              loss='mean_squared_error',
              metrics=[MeanSquaredError(),
                       rmse])

# Menampilkan summary model
model.summary()

train_ratings = train_ratings.astype(np.float32)

# Melatih model
history = model.fit(
    [train_user_input, train_item_input],
    train_ratings,
    epochs=40,
    batch_size=64
)

import numpy as np

# Fungsi untuk mendapatkan rekomendasi film berdasarkan prediksi rating
def get_movie_recommendations(user_id, num_recommendations=10):
    # Semua ID film yang tersedia
    movseri_ids = np.arange(num_items)

    # Membuat array user_id dengan panjang sama
    user_ids = np.full_like(movseri_ids, user_id)

    # Prediksi rating untuk semua (user_id, movie_id)
    predictions = model.predict([user_ids, movseri_ids], verbose=0).flatten()

    # Ambil ID film dengan rating tertinggi
    top_indices = predictions.argsort()[::-1][:num_recommendations]
    recommended_ids = movseri_ids[top_indices]

    # Ambil data film dari df_CF (berdasarkan movseri_id)
    recommended_movies = df_CF[df_CF['movseri_id'].isin(recommended_ids)][['title', 'genres']].drop_duplicates()

    return recommended_movies.reset_index(drop=True)

# Contoh: Mendapatkan 10 rekomendasi film untuk user tertentu
user_id = 70  # Ganti dengan ID user yang ingin diuji

# Ambil rekomendasi dari fungsi
recommended_movies = get_movie_recommendations(user_id, num_recommendations=10)

# Tampilkan hasil rekomendasi
print(f"Top 10 rekomendasi film untuk user {user_id}:\n")
for i, row in recommended_movies.iterrows():
    print(f"{i+1}. Title: {row['title']}  |  Genre: {row['genres']}")

"""####**Evaluasi Collaborative Filtering**"""

import matplotlib.pyplot as plt

# Mengambil data MSE dan RMSE dari history
mse = history.history['mean_squared_error']
rmse = history.history['rmse']

# Membuat plot MSE selama training
plt.figure(figsize=(12, 6))

# Plot MSE
plt.subplot(1, 2, 1)
plt.plot(mse)
plt.title('Model Mean Squared Error (MSE) During Training')
plt.xlabel('Epoch')
plt.ylabel('MSE')

# Plot RMSE
plt.subplot(1, 2, 2)
plt.plot(rmse)
plt.title('Model Root Mean Squared Error (RMSE) During Training')
plt.xlabel('Epoch')
plt.ylabel('RMSE')

plt.tight_layout()
plt.show()